apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: migration parse
    kompose.version: 1.16.0 (0c01309)
  labels:
    io.kompose.service: mop-article-pub-center
  name: mop-article-pub-center
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mop-article-pub-center
  template:
    metadata:
      labels:
        io.kompose.service: mop-article-pub-center
    spec:
      containers:
        - env:
            - name: REDIS_MODE
              value: "single"
            - name: PUBLISH_ENV
              value: 'ol'
            - name: HTTP_PORT
              value: '8080'
            - name: ROUTE_MODE
              value: 'debug'
            - name: LOG_MODE
              value: 'debug'
            - name: MONGO_URL
              value: {{ .Values.mongodb.uri | quote }}
            - name: DB_NAME
              value: 'mop-article-pub-center-private'
            - name: REDIS_URL
              value: {{ .Values.redis.uri | quote }}
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.password | quote }}
            - name: REDIS_PWD
              value: {{ .Values.redis.password | quote }}
            - name: MAX_REDIS_CLIENT_NUM
              value: '20'
            - name: CRON_KEY_PRE
              value: 'article_publish_cron_private_'
            - name: KAFKA_ADDR
              value: {{ .Values.kafka.addr }}
            - name: NOTIFY_TOPIC
              value: 'mop_private_notify_data_topic'
            - name: NOTIFY_URL
              value: 'http://mop-notify:8080'
            - name: AUTH_CHECK_URL
              value: 'http://mop-account-system:8080'
            - name: ACCOUNT_INFO_URL
              value: 'http://mop-account-system:8080/api/v1/mop/applets-ecol-account/operation/worker/detail/'
            - name: WECHAT_TOKEN_URL
              value: 'https://api.weixin.qq.com/cgi-bin/token'
            - name: WECHAT_APP_CODE_URL
              value: 'https://api.weixin.qq.com/wxa/getwxacodeunlimit'
            - name: ALLOW_APPLY_ID_NUM
              value: '10'
            - name: ALLOW_BIND_NUM
              value: '10'
            - name: ALLOW_MEM_NUM
              value: '99'
            - name: PER_ALLOW_APPID_NUM
              value: '2'
            - name: PER_ALLOW_BIND_NUM
              value: '1'
            - name: PER_ALLOW_MEM_NUM
              value: '0'
            - name: ZIPKIN_URL
              value: ''
          image: {{ .Values.images.mop_article_pub_center }}
          imagePullPolicy: IfNotPresent
          name: mop-article-pub-center
          resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: {{ .Values.images.pullSecrets }}
