apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: migration parse
    kompose.version: 1.16.0 (0c01309)
  labels:
    io.kompose.service: mop-private-init-server
  name: mop-private-init-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mop-private-init-server
  template:
    metadata:
      labels:
        io.kompose.service: mop-private-init-server
    spec:
      containers:
      - env:
        - name: CONSUL_HTTP_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: CONSUL_TAG
          value: mop-finstore
        - name: HTTP_PORT
          value: '8080'
        - name: NETDISK_URL
          value: 'http://netdisk:9999'
        - name: MONGO_URL
          value: {{ .Values.mongodb.uri | quote }}
        - name: ORGAN_NAME
          value: {{ .Values.organ_name }}
        - name: DB_NAME
          value: 'mop-account-system-private'
        - name: NETDISK_USER
          value: '@netdisk:mp.finogeeks.com'
        - name: AUTO_REGISTER
          value: "1"
        - name: ORGAN_PATH
          value: community
        image: {{ .Values.images.mop_private_init_server }}
        imagePullPolicy: IfNotPresent
        name: mop-private-init-server
        resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: {{ .Values.images.pullSecrets }}
