apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mop-article-pub-center
  name: mop-article-pub-center
spec:
  ports:
    - name: "port"
      port: 8080
      targetPort: 8080
    - name: "monitor"
      port: 9092
      targetPort: 9092
  selector:
    io.kompose.service: mop-article-pub-center