apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: migration parse
    kompose.version: 1.16.0 (0c01309)
  labels:
    io.kompose.service: mop-rule-engine-svr
  name: mop-rule-engine-svr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mop-rule-engine-svr
  template:
    metadata:
      labels:
        io.kompose.service: mop-rule-engine-svr
    spec:
      containers:
        - env:
            - name: CONSUL_HTTP_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: CONSUL_TAG
              value: mop-finstore
            - name: REDIS_MODE
              value: "single"
            - name: PUBLISH_ENV
              value: 'saas'
            - name: ROUTE_MODE
              value: 'debug'
            - name: LOG_MODE
              value: 'debug'
            - name: MONGO_URL
              value: {{ .Values.mongodb.uri | quote }}
            - name: DB_NAME
              value: 'mop-rule-engine'
            - name: REDIS_URL
              value: {{ .Values.redis.uri | quote }}
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.password | quote }}
            - name: NOTIFY_TOPIC
              value: 'mop_private_notify_data_topic'
            - name: NETDISK_HOST
              value: 'http://netdisk:9999'
            - name: NETDISK_UPLOAD_URL
              value: '/api/v1/netdisk/upload/self'
            - name: KAFKA_ADDR
              value: {{ .Values.kafka.addr }}
            - name: KAFKA_DATA_LOG_TOPIC
              value: 'mop_private_operation_log'
            - name: NETDISK_DOWN_URL
              value: '/api/v1/netdisk/download/'
            - name: GET_GRAY_STS_VER_LIST
              value: /api/v1/mop/finstore/rule-engine/statics/ver-list
          image: {{ .Values.images.mop_rule_engine_svr }}
          imagePullPolicy: IfNotPresent
          name: mop-rule-engine-svr
          resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: {{ .Values.images.pullSecrets }}
