apiVersion: v1
kind: Service
metadata:
  name: mop-applet-build
  labels:
    io.kompose.service: mop-applet-build
spec:
  ports:
  - port: 8080
    name: port
    targetPort: 8080
  selector:
    io.kompose.service: mop-applet-build
