apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: migration parse
    kompose.version: 1.16.0 (0c01309)
  labels:
    io.kompose.service: mop-app-gray-statistics-center
  name: mop-app-gray-statistics-center
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mop-app-gray-statistics-center
  template:
    metadata:
      labels:
        io.kompose.service: mop-app-gray-statistics-center
    spec:
      containers:
        - env:
            - name: HTTP_PORT
              value: '8080'
            - name: MONGO_URL
              value: {{ .Values.mongodb.uri | quote }}
            - name: DB_NAME
              value: 'mop-private-app-gray-statistics-center'
            - name: REPORT_DATA_TOPIC
              value: 'mop_private_data_report'
          image: {{ .Values.images.mop_app_gray_statistics_center }}
          imagePullPolicy: IfNotPresent
          name: mop-app-gray-statistics-center
          resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: {{ .Values.images.pullSecrets }}
