apiVersion: v1
kind: Service
metadata:
  name: mop-app-manage-svr
  labels:
    io.kompose.service: mop-app-manage-svr
spec:
  ports:
  - port: 8080
    name: port
    targetPort: 8080
  - port: 9092
    name: monitor
    targetPort: 9092
  selector:
    io.kompose.service: mop-app-manage-svr
