apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: migration parse
    kompose.version: 1.16.0 (0c01309)
  labels:
    io.kompose.service: mop-notify
  name: mop-notify
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mop-notify
  template:
    metadata:
      labels:
        io.kompose.service: mop-notify
    spec:
      containers:
      - env:
        - name: HTTP_PORT
          value: '8080'
        - name: MONGO_URL
          value: {{ .Values.mongodb.uri | quote }}
        - name: DB_NAME
          value: 'mop-applets-ecol-notify-private'
        - name: HTTP_MODE
          value: 'debug'
        - name: LOG_MODE
          value: 'debug'
        - name: KAFKA_ADDR
          value: {{ .Values.kafka.addr }}
        - name: NOTIFY_DATA_TOPIC
          value: 'mop_private_notify_data_topic'
        - name: ZIPKIN_URL
          value: ''
        image: {{ .Values.images.mop_notify }}
        imagePullPolicy: IfNotPresent
        name: mop-notify
        resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: {{ .Values.images.pullSecrets }}
